#!/usr/bin/env python

# synchronize_reset.py script creates a Verilog Snippet for synchronizing an asynchronous reset.
# To call this script in a Verilog file it should follow the following pattern:
#   `include "synchronize_reset_{prefix}.vs" // arst_i (active-low), sync_reset (active-high), clock = clk_i
#
# Default values are:
#   arst_i (active-low) for the asynchronous reset
#   sync_reset (active-low) for the synchronous reset
#   clock = clk_i

import sys, re

try:
    from VeriSnip.vs_colours import *
except ImportError:
    # Fallback if VeriSnip module is not found
    ERROR = "\033[91m"
    def vs_print(color, msg):
        print(f"{color}{msg}\033[0m")

vs_name_suffix = sys.argv[1].removesuffix(".vs")
vs_name = f"synchronize_reset_{vs_name_suffix}.vs"

def write_vs(string="", file_name=None):
    with open(file_name, "w") as file:
        file.write(string)

def verilog_string(prefix, arst, arst_type, sync_reset, sync_reset_type, clock):
    if arst_type == "active-low":
        arst_edge = "negedge"
        arst_cond = f"!{arst}"
    else:
        arst_edge = "posedge"
        arst_cond = arst
        
    if sync_reset_type == "active-low":
        sync_assert_val = "1'b0"
        sync_deassert_val = "1'b1"
    else:
        sync_assert_val = "1'b1"
        sync_deassert_val = "1'b0"

    reg1 = f"{prefix}_rst_reg1"
    reg2 = f"{prefix}_rst_reg2"

    code = f"""
  // Generated by synchronize_reset.py: {arst_type.upper()} Asynchronous Reset to {sync_reset_type.upper()} Synchronous Reset
  logic {reg1}, {reg2};
  always_ff @(posedge {clock} or {arst_edge} {arst}) begin
    if ({arst_cond}) begin
      // Asynchronous Assert:
      // When {arst} asserts, both registers are immediately set to the asserted value.
      {reg1} <= {sync_assert_val};
      {reg2} <= {sync_assert_val};
    end else begin
      // Synchronous De-assert:
      // When {arst} de-asserts, the de-asserted value shifts through the pipeline.
      {reg1} <= {sync_deassert_val};
      {reg2} <= {reg1};
    end
  end\n
  assign {sync_reset} = {reg2};
"""
    return code

def parse_arguments():
    if len(sys.argv) < 2:
        vs_print(ERROR, "Not enough arguments.")
        exit(1)

    arst = "arst_i"
    arst_type = "active-low"
    sync_reset = "sync_reset"
    sync_reset_type = "active-low"
    clock = "clk_i"

    # Check if any argument contains "//"
    has_double_slash = any("//" in arg for arg in sys.argv[1:])
    if has_double_slash:
        args_str = ""
        # Find the argument with "//"
        for _, arg in enumerate(sys.argv):
            if "//" in arg:
                args_str = arg[arg.index("//")+2:]
                break
                
        args = [a.strip() for a in args_str.split(',')]
        
        if len(args) > 0 and args[0]:
            m = re.match(r'(\w+)(?:\s*\((active-low|active-high)\))?', args[0])
            if m:
                arst = m.group(1)
                if m.group(2):
                    arst_type = m.group(2)

        if len(args) > 1 and args[1]:
            m = re.match(r'(\w+)(?:\s*\((active-low|active-high)\))?', args[1])
            if m:
                sync_reset = m.group(1)
                if m.group(2):
                    sync_reset_type = m.group(2)

        if len(args) > 2 and args[2]:
            clk_str = args[2]
            if "=" in clk_str:
                clock = clk_str.split("=")[1].strip()
            else:
                clock = clk_str.strip()
    else:
        # If no // is found, just use defaults
        pass

    return arst, arst_type, sync_reset, sync_reset_type, clock

if __name__ == "__main__":
    arst, arst_type, sync_reset, sync_reset_type, clock = parse_arguments()
    vs_content = verilog_string(vs_name_suffix, arst, arst_type, sync_reset, sync_reset_type, clock)
    write_vs(vs_content, vs_name)
